version: "3.9"

services:
  django-db:
    image: postgres:16
    environment:
      POSTGRES_DB: djangoapp
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - django_db_data:/var/lib/postgresql/data
    networks:
      - sso-example-net

  django-app:
    build: .
    env_file:
      - .env
    ports:
      - "8211:8000"
    depends_on:
      django-db:
        condition: service_healthy
    networks:
      - sso-example-net

volumes:
  django_db_data:

networks:
  sso-example-net:
    external: true

